VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.network :forwarded_port, guest: 9418, host: 9418

  # sharing git-recipes folder on Windows as Host VM
  config.vm.synced_folder "c:\\git-recipes", "/pub/git"

  # sharing git-recipes folder on Unix-like system as Host VM
  #config.vm.synced_folder "/some/where/git-recipes", "/pub/git"

end
